config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  namespace :admin do
    resource "dashboard", controller: :dashboard, only: %i[show]
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: {
    0: :draft,
    1: :published
  }
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_action :authenticate_admin!
    layout "admin"

    private

    def authenticate_admin!
      #redirect_to root_path unless false
    end
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < BaseController
    def show
    end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    def index
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/products/index.html.erb
<div class="flex items-center">
  <div class="ml-auto flex items-center gap-2">
    filter

    <%= render UI::ButtonComponent.new size: :sm, variant: :outline, class: "h-8 gap-1" do %>
      <%= lucide_icon "file", class: "h-3.5 w-3.5" %>
      <span class="sr-only sm:not-sr-only sm:whitespace-nowrap">
        Export
      </span>
    <% end %>

    <%= link_to new_admin_product_path, class: UI::ButtonComponent.button_variants(size: :sm, variant: :outline, classes: "h-8 gap-1") do %>
      <%= lucide_icon "plus-circle", class: "h-3.5 w-3.5" %>
      <span class="sr-only sm:not-sr-only sm:whitespace-nowrap">
        Add Product
      </span>
    <% end %>
  </div>
</div>

<%= render UI::CardComponent.new do |card| %>
  <%= card.with_header do |header| %>
    <%= header.with_title do %>
      Products
    <% end %>

    <%= header.with_description do %>
      Manage your products and view their sales performance.
    <% end %>
  <% end %>
  <%= card.with_body do %>
    <%= render UI::TableComponent.new do |table| %>
      <%= table.with_header do |header| %>
        <%= header.with_row do |row| %>
          <%= row.with_head do %>
            Name
          <% end %>
          <%= row.with_head do %>
            Status
          <% end %>
          <%= row.with_head do %>
            Actions
          <% end %>
        <% end %>
      <% end %>

      <%= table.with_body do |body| %>
        <%= body.with_row do |row| %>
          <%= row.with_cell do %>
            Dog
          <% end %>
          <%= row.with_cell do %>
            Happy
          <% end %>
          <%= row.with_cell do %>
            <%= render UI::DropdownComponent.new do |dropdown| %>
              <% dropdown.with_trigger do %>
                <%= render UI::ButtonComponent.new variant: :ghost,
                  size: :icon,
                  aria: { 'haspopup': true },
                  data: { 
                    "ui--popover-target": "trigger",
                    action: "click->ui--popover#toggle" 
                  } do %>
                  <%= lucide_icon "more-horizontal", class: "w-4 h-4" %>
                <% end %>
              <% end %>

              <%= dropdown.with_body side: :end, class: "w-56" do |body| %>
                <%= body.with_label do %>
                  Actions
                <% end %>
                <%= body.with_item do %>
                  Edit
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/products/new.html.erb
<div>
  New Form
</div>

app/views/home/index.html.erb
<%= render UI::AlertComponent.new do |alert| %>
  <%= alert.with_title do %>
    title
  <% end %>
  <%= alert.with_description do %>
    DUDE!
  <% end %>
<% end %>

<%= render UI::AvatarComponent.new do |avatar| %>
  <%= avatar.with_image(src: "https://github.com/shadcn.png", alt: "test") %>
  <%= avatar.with_fallback do %>
    DUDE!
  <% end %>
<% end %>

<%= render UI::CardComponent.new do |card| %>
  <%= card.with_header do |header| %>
    <%= header.with_title do %>
      Card Title
    <% end %>
    <%= header.with_description do %>
      Card Description
    <% end %>
  <% end %>
  <%= card.with_body do |body| %>
    body
  <% end %>
  <%= card.with_footer do %>
    Footer
  <% end %>
<% end %>

<%= render UI::ButtonComponent.new(data: { action: "click->ui--dialog#open" }) do %>
  Open dialog
<% end %>

<%= render UI::DialogComponent.new do |dialog| %>
  <%= dialog.with_body do |body| %>
    <%= body.with_header do |header| %>
      <%= header.with_title do %>
        Dialog Title
      <% end %>
      <%= header.with_description do %>
        Dialog description
      <% end %>
    <% end %>
    dialog body

    <%= body.with_footer do %>
      Dialog footer
    <% end %>
  <% end %>
<% end %>

<%= render UI::InputComponent.new(type: "text", placeholder: "dog") %>
Number
<%= render UI::InputComponent.new(type: "number") %>

<%= render UI::ButtonComponent.new(class_name: "bg-yellow-300") do %>
  hello
<% end %>

<%= render UI::ButtonComponent.new(size: :lg, variant: :destructive) do %>
  hello
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html class="dark">
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="flex min-h-screen w-full flex-col bg-muted/40">
      <%= render Admin::SidebarComponent.new %>
      <div class="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
        <%= render Admin::HeaderComponent.new %>
        <main class="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body 
    data-controller="ui--dialog"
    data-ui--dialog-state-value="closed"
    data-action="animationend->ui--dialog#hide click@window->ui--dialog#closeByOutsideClick keydown@window->ui--dialog#closeByKey"
    <%= yield %>
  </body>
</html>